-- 코드를 입력하세요

SELECT HOUR1, NVL(COUNTS, 0) FROM (
(SELECT LEVEL-1 AS HOUR1 FROM DUAL CONNECT BY LEVEL BETWEEN 0 AND 24) A
LEFT OUTER JOIN
(SELECT HOUR2, COUNT(HOUR2) AS COUNTS FROM
(SELECT EXTRACT (HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR2
FROM ANIMAL_OUTS)
GROUP BY HOUR2) B
ON A.HOUR1 = B.HOUR2
)
ORDER BY A.HOUR1