SELECT B.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT A
LEFT OUTER JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE TO_CHAR(B.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY B.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, B.PRODUCT_ID;